package com.volunteer.demo.DO;

import java.io.Serializable;

public class YcGroupActivity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_group_activity.group_activity_id
     *
     * @mbggenerated
     */
    private Long groupActivityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_group_activity.group_id
     *
     * @mbggenerated
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_group_activity.activity_id
     *
     * @mbggenerated
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_group_activity.activity_creater
     *
     * @mbggenerated
     */
    private Integer activityCreater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yc_group_activity
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_group_activity.group_activity_id
     *
     * @return the value of yc_group_activity.group_activity_id
     *
     * @mbggenerated
     */
    public Long getGroupActivityId() {
        return groupActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_group_activity.group_activity_id
     *
     * @param groupActivityId the value for yc_group_activity.group_activity_id
     *
     * @mbggenerated
     */
    public void setGroupActivityId(Long groupActivityId) {
        this.groupActivityId = groupActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_group_activity.group_id
     *
     * @return the value of yc_group_activity.group_id
     *
     * @mbggenerated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_group_activity.group_id
     *
     * @param groupId the value for yc_group_activity.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_group_activity.activity_id
     *
     * @return the value of yc_group_activity.activity_id
     *
     * @mbggenerated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_group_activity.activity_id
     *
     * @param activityId the value for yc_group_activity.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_group_activity.activity_creater
     *
     * @return the value of yc_group_activity.activity_creater
     *
     * @mbggenerated
     */
    public Integer getActivityCreater() {
        return activityCreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_group_activity.activity_creater
     *
     * @param activityCreater the value for yc_group_activity.activity_creater
     *
     * @mbggenerated
     */
    public void setActivityCreater(Integer activityCreater) {
        this.activityCreater = activityCreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_group_activity
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", groupActivityId=").append(groupActivityId);
        sb.append(", groupId=").append(groupId);
        sb.append(", activityId=").append(activityId);
        sb.append(", activityCreater=").append(activityCreater);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}