package com.volunteer.demo.DO;

import java.io.Serializable;
import java.util.Date;

public class YcUserGroup implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_user_group.user_group_id
     *
     * @mbggenerated
     */
    private Long userGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_user_group.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_user_group.group_id
     *
     * @mbggenerated
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_user_group.group_role
     *
     * @mbggenerated
     */
    private Integer groupRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_user_group.entry_date
     *
     * @mbggenerated
     */
    private Date entryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yc_user_group
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_user_group.user_group_id
     *
     * @return the value of yc_user_group.user_group_id
     *
     * @mbggenerated
     */
    public Long getUserGroupId() {
        return userGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_user_group.user_group_id
     *
     * @param userGroupId the value for yc_user_group.user_group_id
     *
     * @mbggenerated
     */
    public void setUserGroupId(Long userGroupId) {
        this.userGroupId = userGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_user_group.user_id
     *
     * @return the value of yc_user_group.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_user_group.user_id
     *
     * @param userId the value for yc_user_group.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_user_group.group_id
     *
     * @return the value of yc_user_group.group_id
     *
     * @mbggenerated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_user_group.group_id
     *
     * @param groupId the value for yc_user_group.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_user_group.group_role
     *
     * @return the value of yc_user_group.group_role
     *
     * @mbggenerated
     */
    public Integer getGroupRole() {
        return groupRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_user_group.group_role
     *
     * @param groupRole the value for yc_user_group.group_role
     *
     * @mbggenerated
     */
    public void setGroupRole(Integer groupRole) {
        this.groupRole = groupRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_user_group.entry_date
     *
     * @return the value of yc_user_group.entry_date
     *
     * @mbggenerated
     */
    public Date getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_user_group.entry_date
     *
     * @param entryDate the value for yc_user_group.entry_date
     *
     * @mbggenerated
     */
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_user_group
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userGroupId=").append(userGroupId);
        sb.append(", userId=").append(userId);
        sb.append(", groupId=").append(groupId);
        sb.append(", groupRole=").append(groupRole);
        sb.append(", entryDate=").append(entryDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}