package com.volunteer.demo.mapper;

import com.volunteer.demo.DO.YcGroupApply;
import com.volunteer.demo.DTO.UserGroupDTO;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface YcGroupApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_group_apply
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long applyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_group_apply
     *
     * @mbggenerated
     */
    int insert(YcGroupApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_group_apply
     *
     * @mbggenerated
     */
    YcGroupApply selectByPrimaryKey(Long applyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_group_apply
     *
     * @mbggenerated
     */
    List<YcGroupApply> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_group_apply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YcGroupApply record);

    /**
     * 查看用户是否重复申请
     */
    Integer countUserApply(Long userId);
}