package com.volunteer.demo.mapper;

import com.volunteer.demo.DO.YcGroupActivity;
import java.util.List;

public interface YcGroupActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_group_activity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long groupActivityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_group_activity
     *
     * @mbggenerated
     */
    int insert(YcGroupActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_group_activity
     *
     * @mbggenerated
     */
    YcGroupActivity selectByPrimaryKey(Long groupActivityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_group_activity
     *
     * @mbggenerated
     */
    List<YcGroupActivity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_group_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YcGroupActivity record);
}