package com.volunteer.demo.mapper;

import com.volunteer.demo.DO.YcUser;
import com.volunteer.demo.DTO.ImageDTO;
import com.volunteer.demo.DTO.RegisterDTO;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface YcUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_user
     *
     * @mbggenerated
     */
    int insert(YcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_user
     *
     * @mbggenerated
     */
    YcUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_user
     *
     * @mbggenerated
     */
    List<YcUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YcUser record);

    YcUser getUser(String userName);

    /**
     * 注册
     * @param dto
     * @return
     */
    int registerUser(RegisterDTO dto);

    /**
     * 上传图片
     * @param dto
     * @return
     */
    int insertImage(ImageDTO dto);

    /**
     * 判断用户名是否存在
     */
    int checkUserName(String userName);
}