package com.volunteer.demo.DO;

import java.io.Serializable;
import java.util.Date;

public class YcActivity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_activity.activity_id
     *
     * @mbggenerated
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_activity.activity_name
     *
     * @mbggenerated
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_activity.activity_introduction
     *
     * @mbggenerated
     */
    private String activityIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_activity.activity_group
     *
     * @mbggenerated
     */
    private Long activityGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_activity.activity_city
     *
     * @mbggenerated
     */
    private String activityCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_activity.activity_status
     *
     * @mbggenerated
     */
    private Integer activityStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_activity.activity_type
     *
     * @mbggenerated
     */
    private Integer activityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_activity.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_activity.activity_leader
     *
     * @mbggenerated
     */
    private Long activityLeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_activity.activity_image
     *
     * @mbggenerated
     */
    private String activityImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yc_activity
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_activity.activity_id
     *
     * @return the value of yc_activity.activity_id
     *
     * @mbggenerated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_activity.activity_id
     *
     * @param activityId the value for yc_activity.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_activity.activity_name
     *
     * @return the value of yc_activity.activity_name
     *
     * @mbggenerated
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_activity.activity_name
     *
     * @param activityName the value for yc_activity.activity_name
     *
     * @mbggenerated
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_activity.activity_introduction
     *
     * @return the value of yc_activity.activity_introduction
     *
     * @mbggenerated
     */
    public String getActivityIntroduction() {
        return activityIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_activity.activity_introduction
     *
     * @param activityIntroduction the value for yc_activity.activity_introduction
     *
     * @mbggenerated
     */
    public void setActivityIntroduction(String activityIntroduction) {
        this.activityIntroduction = activityIntroduction == null ? null : activityIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_activity.activity_group
     *
     * @return the value of yc_activity.activity_group
     *
     * @mbggenerated
     */
    public Long getActivityGroup() {
        return activityGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_activity.activity_group
     *
     * @param activityGroup the value for yc_activity.activity_group
     *
     * @mbggenerated
     */
    public void setActivityGroup(Long activityGroup) {
        this.activityGroup = activityGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_activity.activity_city
     *
     * @return the value of yc_activity.activity_city
     *
     * @mbggenerated
     */
    public String getActivityCity() {
        return activityCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_activity.activity_city
     *
     * @param activityCity the value for yc_activity.activity_city
     *
     * @mbggenerated
     */
    public void setActivityCity(String activityCity) {
        this.activityCity = activityCity == null ? null : activityCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_activity.activity_status
     *
     * @return the value of yc_activity.activity_status
     *
     * @mbggenerated
     */
    public Integer getActivityStatus() {
        return activityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_activity.activity_status
     *
     * @param activityStatus the value for yc_activity.activity_status
     *
     * @mbggenerated
     */
    public void setActivityStatus(Integer activityStatus) {
        this.activityStatus = activityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_activity.activity_type
     *
     * @return the value of yc_activity.activity_type
     *
     * @mbggenerated
     */
    public Integer getActivityType() {
        return activityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_activity.activity_type
     *
     * @param activityType the value for yc_activity.activity_type
     *
     * @mbggenerated
     */
    public void setActivityType(Integer activityType) {
        this.activityType = activityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_activity.create_time
     *
     * @return the value of yc_activity.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_activity.create_time
     *
     * @param createTime the value for yc_activity.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_activity.activity_leader
     *
     * @return the value of yc_activity.activity_leader
     *
     * @mbggenerated
     */
    public Long getActivityLeader() {
        return activityLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_activity.activity_leader
     *
     * @param activityLeader the value for yc_activity.activity_leader
     *
     * @mbggenerated
     */
    public void setActivityLeader(Long activityLeader) {
        this.activityLeader = activityLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_activity.activity_image
     *
     * @return the value of yc_activity.activity_image
     *
     * @mbggenerated
     */
    public String getActivityImage() {
        return activityImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_activity.activity_image
     *
     * @param activityImage the value for yc_activity.activity_image
     *
     * @mbggenerated
     */
    public void setActivityImage(String activityImage) {
        this.activityImage = activityImage == null ? null : activityImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_activity
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", activityId=").append(activityId);
        sb.append(", activityName=").append(activityName);
        sb.append(", activityIntroduction=").append(activityIntroduction);
        sb.append(", activityGroup=").append(activityGroup);
        sb.append(", activityCity=").append(activityCity);
        sb.append(", activityStatus=").append(activityStatus);
        sb.append(", activityType=").append(activityType);
        sb.append(", createTime=").append(createTime);
        sb.append(", activityLeader=").append(activityLeader);
        sb.append(", activityImage=").append(activityImage);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}