package com.volunteer.demo.DO;

import org.apache.ibatis.annotations.Mapper;

import java.io.Serializable;
import java.util.Date;

public class YcGroup implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_group.group_id
     *
     * @mbggenerated
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_group.group_name
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_group.group_city
     *
     * @mbggenerated
     */
    private String groupCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_group.group_introduction
     *
     * @mbggenerated
     */
    private String groupIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_group.group_leader
     *
     * @mbggenerated
     */
    private Long groupLeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_group.group_requirement
     *
     * @mbggenerated
     */
    private String groupRequirement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_group.group_image
     *
     * @mbggenerated
     */
    private String groupImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_group.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_group.group_status
     *
     * @mbggenerated
     */
    private Integer groupStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_group.group_qq
     *
     * @mbggenerated
     */
    private String groupQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yc_group
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_group.group_id
     *
     * @return the value of yc_group.group_id
     *
     * @mbggenerated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_group.group_id
     *
     * @param groupId the value for yc_group.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_group.group_name
     *
     * @return the value of yc_group.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_group.group_name
     *
     * @param groupName the value for yc_group.group_name
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_group.group_city
     *
     * @return the value of yc_group.group_city
     *
     * @mbggenerated
     */
    public String getGroupCity() {
        return groupCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_group.group_city
     *
     * @param groupCity the value for yc_group.group_city
     *
     * @mbggenerated
     */
    public void setGroupCity(String groupCity) {
        this.groupCity = groupCity == null ? null : groupCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_group.group_introduction
     *
     * @return the value of yc_group.group_introduction
     *
     * @mbggenerated
     */
    public String getGroupIntroduction() {
        return groupIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_group.group_introduction
     *
     * @param groupIntroduction the value for yc_group.group_introduction
     *
     * @mbggenerated
     */
    public void setGroupIntroduction(String groupIntroduction) {
        this.groupIntroduction = groupIntroduction == null ? null : groupIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_group.group_leader
     *
     * @return the value of yc_group.group_leader
     *
     * @mbggenerated
     */
    public Long getGroupLeader() {
        return groupLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_group.group_leader
     *
     * @param groupLeader the value for yc_group.group_leader
     *
     * @mbggenerated
     */
    public void setGroupLeader(Long groupLeader) {
        this.groupLeader = groupLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_group.group_requirement
     *
     * @return the value of yc_group.group_requirement
     *
     * @mbggenerated
     */
    public String getGroupRequirement() {
        return groupRequirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_group.group_requirement
     *
     * @param groupRequirement the value for yc_group.group_requirement
     *
     * @mbggenerated
     */
    public void setGroupRequirement(String groupRequirement) {
        this.groupRequirement = groupRequirement == null ? null : groupRequirement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_group.group_image
     *
     * @return the value of yc_group.group_image
     *
     * @mbggenerated
     */
    public String getGroupImage() {
        return groupImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_group.group_image
     *
     * @param groupImage the value for yc_group.group_image
     *
     * @mbggenerated
     */
    public void setGroupImage(String groupImage) {
        this.groupImage = groupImage == null ? null : groupImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_group.create_time
     *
     * @return the value of yc_group.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_group.create_time
     *
     * @param createTime the value for yc_group.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_group.group_status
     *
     * @return the value of yc_group.group_status
     *
     * @mbggenerated
     */
    public Integer getGroupStatus() {
        return groupStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_group.group_status
     *
     * @param groupStatus the value for yc_group.group_status
     *
     * @mbggenerated
     */
    public void setGroupStatus(Integer groupStatus) {
        this.groupStatus = groupStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_group.group_qq
     *
     * @return the value of yc_group.group_qq
     *
     * @mbggenerated
     */
    public String getGroupQq() {
        return groupQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_group.group_qq
     *
     * @param groupQq the value for yc_group.group_qq
     *
     * @mbggenerated
     */
    public void setGroupQq(String groupQq) {
        this.groupQq = groupQq == null ? null : groupQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_group
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", groupId=").append(groupId);
        sb.append(", groupName=").append(groupName);
        sb.append(", groupCity=").append(groupCity);
        sb.append(", groupIntroduction=").append(groupIntroduction);
        sb.append(", groupLeader=").append(groupLeader);
        sb.append(", groupRequirement=").append(groupRequirement);
        sb.append(", groupImage=").append(groupImage);
        sb.append(", createTime=").append(createTime);
        sb.append(", groupStatus=").append(groupStatus);
        sb.append(", groupQq=").append(groupQq);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}